<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-J9CTNA9" failures="1" tests="3" name="Test" time="62.634" errors="0" timestamp="2022-07-27T06:53:09 IST">
  <testcase classname="TestClasses.VerifyUserCanLogIn" name="verifyUserCanLogIn" time="4.14"/>
  <testcase classname="TestClasses.verifyUserCanAddNewAddress" name="verifyUserCanGoToProfilePage" time="5.586"/>
  <testcase classname="TestClasses.verifyUserCanAddNewAddress" name="verifyUserCanAddAddress" time="19.587">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at TestClasses.verifyUserCanAddNewAddress.verifyUserCanAddAddress(verifyUserCanAddNewAddress.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanAddAddress -->
</testsuite> <!-- Test -->
